// <auto-generated />
using System;
using Kreislauf.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kreislauf.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240705074914_AddKaSaLTables")]
    partial class AddKaSaLTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Krsilaufdb.Models.Klasse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Schule_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Schule_Id");

                    b.ToTable("Klasse");
                });

            modelBuilder.Entity("Krsilaufdb.Models.Lauf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double?>("RundenAnzahl")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Lauf");
                });

            modelBuilder.Entity("Krsilaufdb.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Geburtsdatum")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Geschlecht")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Klasse_Id")
                        .HasColumnType("int");

                    b.Property<int>("Lauf_Id")
                        .HasColumnType("int");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Klasse_Id");

                    b.HasIndex("Lauf_Id");

                    b.ToTable("Personen");
                });

            modelBuilder.Entity("Krsilaufdb.Models.Schule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Stadt")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Schule");
                });

            modelBuilder.Entity("Krsilaufdb.Models.Klasse", b =>
                {
                    b.HasOne("Krsilaufdb.Models.Schule", "Schule")
                        .WithMany("Klassen")
                        .HasForeignKey("Schule_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schule");
                });

            modelBuilder.Entity("Krsilaufdb.Models.Person", b =>
                {
                    b.HasOne("Krsilaufdb.Models.Klasse", "Klasse")
                        .WithMany("Personen")
                        .HasForeignKey("Klasse_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Krsilaufdb.Models.Lauf", "Lauf")
                        .WithMany("Personen")
                        .HasForeignKey("Lauf_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klasse");

                    b.Navigation("Lauf");
                });

            modelBuilder.Entity("Krsilaufdb.Models.Klasse", b =>
                {
                    b.Navigation("Personen");
                });

            modelBuilder.Entity("Krsilaufdb.Models.Lauf", b =>
                {
                    b.Navigation("Personen");
                });

            modelBuilder.Entity("Krsilaufdb.Models.Schule", b =>
                {
                    b.Navigation("Klassen");
                });
#pragma warning restore 612, 618
        }
    }
}
